# Generated by Django 5.0.2 on 2024-03-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departments', models.CharField(max_length=100)),
                ('Doctors', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
