# Generated by Django 5.0.2 on 2024-03-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='name',
            new_name='full_name',
        ),
    ]
