# Generated by Django 5.0.2 on 2024-04-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_name_list_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
