# Generated by Django 5.0.2 on 2024-04-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='Phone',
            field=models.CharField(max_length=12),
        ),
    ]
