# Generated by Django 5.0.2 on 2024-04-03 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_list_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150)),
                ('department_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.SmallIntegerField()),
                ('education_status', models.CharField(max_length=150)),
                ('work_experience', models.SmallIntegerField()),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('doctor_description', models.TextField()),
                ('avialiable_work_hours', models.SmallIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.department')),
            ],
        ),
    ]
