# Generated by Django 5.0.2 on 2024-04-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_department_doctordetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='department_images/')),
            ],
        ),
    ]
