# Generated by Django 5.0.2 on 2024-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_img_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img_Department',
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department_images/'),
        ),
    ]
