# Generated by Django 5.0.2 on 2024-04-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_department_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
    ]
