# Generated by Django 5.0.2 on 2024-08-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_department_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='Departments',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='list',
            name='Doctors',
            field=models.CharField(max_length=250),
        ),
    ]
