# Generated by Django 5.0.2 on 2024-08-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_list_departments_alter_list_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetail',
            name='image',
            field=models.ImageField(default='female.jpg', upload_to='doctor_images/'),
        ),
        migrations.AlterField(
            model_name='list',
            name='Departments',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='Doctors',
            field=models.CharField(max_length=100),
        ),
    ]
