# Generated by Django 5.0.2 on 2024-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_alter_doctordetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.TimeField(max_length=50),
        ),
    ]
