# Generated by Django 5.0.2 on 2024-08-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_alter_list_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
